import ImageWatch from "../../assets/icons/appleWatch6.png";
import type { StockProps } from "../stock/component/StockList";

export const StockData: StockProps[] = [
    {
        id: 1,
        img: ImageWatch,
        name: "Apple Watch Series 4",
        category: "Digital Products",
        price: 690.0,
        piece: 63,
        colors: ["#000000", "#FFFFFF", "#FF5733", "#4343EE"],
    },
    {
        id: 2,
        img: ImageWatch,
        name: "Apple Watch Series 5",
        category: "Digital Product",
        price: 720.0,
        piece: 45,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },
    {
        id: 3,
        img: ImageWatch,
        name: "Apple Watch Series 6",
        category: "Digital Product",
        price: 750.0,
        piece: 30,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },
    {
        id: 4,
        img: ImageWatch,
        name: "Apple Watch SE",
        category: "Digital Product",
        price: 680.0,
        piece: 50,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },
    {
        id: 5,
        img: ImageWatch,
        name: "Apple Watch Series 7",
        category: "Digital Product",
        price: 800.0,
        piece: 20,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },
    {
        id: 6,
        img: ImageWatch,
        name: "Apple Watch Series 4",
        category: "Digital Products",
        price: 690.0,
        piece: 63,
        colors: ["#000000", "#FFFFFF", "#FF5733", "#4343EE"],
    },
    {
        id: 7,
        img: ImageWatch,
        name: "Apple Watch Series 5",
        category: "Digital Product",
        price: 720.0,
        piece: 45,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },
    {
        id: 8,
        img: ImageWatch,
        name: "Apple Watch Series 6",
        category: "Digital Product",
        price: 750.0,
        piece: 30,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },
    {
        id: 9,
        img: ImageWatch,
        name: "Apple Watch SE",
        category: "Digital Product",
        price: 680.0,
        piece: 50,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },
    {
        id: 10,
        img: ImageWatch,
        name: "Apple Watch Series 7",
        category: "Digital Product",
        price: 800.0,
        piece: 20,
        colors: ["#000000", "#FFFFFF", "#FF5733"],
    },

];
